# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pdp3nhYphdjujkPkpROgQd0M0pkjERbS
"""

import numpy as np
from flask import Flask,request, jsonify, render_template
import pickle

app=Flask(__name__)

load_SalaryPred=pickle.load(open('Deploy_SalaryPrediction.pkl','rb'))

@app.route('/')
def home():
  return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
  features=[ int(x) for x in request.form.values()]
  main_features=[np.array(features)]
  prediction=load_SalaryPred.predict(main_features)
  return render_template('index.html',prediction_text='prediction is ${}'.format(prediction))

if __name__=="__main__":
  app.run(debug=True)