# -*- coding: utf-8 -*-
"""Deploy_SalaryPrediction.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SvXnJFu5SPTxO7NniDrG0E3R9pBlrUV
"""

import pandas as pd
df=pd.read_csv("hiring.csv")
df.head()

df.isnull().sum()

df["test_score"]=df["test_score"].fillna(df["test_score"].mean())

df.isnull().sum()

df

def convert_exp_word_to_int(word):
  exp_dict={'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10,'eleven':11,'twelve':12,'0':0}
  return exp_dict[word]

df["experience"]=df["experience"].apply(lambda x: convert_exp_word_to_int(x))
df

X=df.iloc[:,0:3]
y=df.iloc[:,3]

X.head()

y.head()

from sklearn.linear_model import LogisticRegression
LogReg=LogisticRegression()
LogReg.fit(X,y)

from sklearn.linear_model import LinearRegression
LinReg=LinearRegression()
LinReg.fit(X,y)

import pickle
pickle.dump(LogReg,open('Deploy_SalaryPrediction.pkl','wb'))

load_salarypred=pickle.load(open('Deploy_SalaryPrediction.pkl','rb'))
print(load_salarypred.predict([[2,9,6]]))